---
- name: Install packages
  hosts: all
  become: yes
  tasks:
    - name: Install my tools
      apt:
        pkg: [mc, tree, net-tools, htop, neofetch, wget, ufw, git, traceroute]
        update_cache: yes
        state: latest
